//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telephone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Adminstrator : ValidationAttribute
    {
        public string Id { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.Text, ErrorMessage = "Please Enter Char Only")]
        [MinLength(3, ErrorMessage = "Name Must be at least 3 Chars")]
        public string Fname { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.Text, ErrorMessage = "Please Enter Char Only")]
        [MinLength(3, ErrorMessage = "Name Must be at least 3 Chars")]
        public string Lname { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.EmailAddress, ErrorMessage = "Please Enter EmailAddress Only")]
        public string Email { get; set; }


        [Required(ErrorMessage = "This filed is required"), DataType(DataType.Password)]
        [MinLength(8, ErrorMessage = "Password Must be at least 8 Chars")]
        public string Password { get; set; }
    }
}