//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telephone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CheckOut1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckOut1()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }

        public int ID_Order { get; set; }
        public string OrderName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string PaymentType { get; set; }
        public string Status { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.Text, ErrorMessage = "Please Enter Char Only")]
        [MinLength(3, ErrorMessage = "Name Must be at least 3 Chars")]
        public string Fname { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.Text, ErrorMessage = "Please Enter Char Only")]
        [MinLength(3, ErrorMessage = "Name Must be at least 3 Chars")]
        public string Lname { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.PhoneNumber, ErrorMessage = "Please Enter Numbers Only")]
       
        public string Phone { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.EmailAddress, ErrorMessage = "Please Enter EmailAddress Only")]
        public string Email { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.Text, ErrorMessage = "Please Enter Char Only")]
        public string Address { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.Text, ErrorMessage = "Please Enter Char Only")]
        public string City { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.CreditCard, ErrorMessage = "Please Enter CreditCard Only")]
        
        public string Credit_Card { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}