//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telephone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Services = new HashSet<Services>();
        }

        public int Id_Company { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.Text, ErrorMessage = "Please Enter Char Only")]
        [MinLength(3, ErrorMessage = "Name Must be at least 3 Chars")]
        public string Fname { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.Text, ErrorMessage = "Please Enter Char Only")]
        [MinLength(3, ErrorMessage = "Name Must be at least 3 Chars")]
        public string Lname { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.EmailAddress, ErrorMessage = "Please Enter EmailAddress Only")]
        public string Email { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.Password)]
        [MinLength(8, ErrorMessage = "Password Must be at least 8 Chars")]
        public string Password { get; set; }

        [Required(ErrorMessage = "This filed is required"), DataType(DataType.PhoneNumber, ErrorMessage = "Please Enter Numbers Only")]
        //[Range(10, 12, ErrorMessage = "Phone number must be between 11 and 12")]
        public string Phone { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
    }
}