//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telephone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Drawing;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }


        public int ProId { get; set; }
        [Required]
        public string brand { get; set; }
        [Required]
        public string model { get; set; }
        public string GPRS { get; set; }
        public string availabality { get; set; }
        public string weight_g { get; set; }
        public string SIM { get; set; }
        public string display_type { get; set; }
        public string display_resolution { get; set; }
        public string OS { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public string memory_card { get; set; }
        public string internal_memory { get; set; }
        public string RAM { get; set; }
        public string primary_camera { get; set; }
        public string secondary_camera { get; set; }
        public string sensors { get; set; }
        public string battery { get; set; }
        public string colors { get; set; }
        public string approx_price_EGP { get; set; }
        [DisplayName("Upload File")]
        [Required]
        public string img { get; set; }
        [Required]
        public HttpPostedFileBase imagefile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}